Add a fix for compiling under GCC 13
Under GCC 13, version 1.3.3 of hdt-cpp fails to compile
hdt-cpp-1.3.3/libhdt/src/util/StopWatch.cpp with the messages:

    error: ‘uint64_t’ was not declared in this scope
    note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?

According to the porting guide for GCC 13, <cstdint> "may need to be
included explicitly when compiling with GCC 13". This commit adds a
compiler flag to always include it. These flags can be removed when a
new version of hdt-cpp is released, as this is already patched upstream.

Fixes <https://github.com/RDFLib/rdflib-hdt/issues/38>